### PR TITLE
pieeprom-2020-05-15.bin - USB mass storage boot beta

### PR DESCRIPTION
**Pull request by timg236**
USB boot also requires updated firmware (start.elf)

### CODE REVIEW

**Comment by timg236** [comment]
@XECDesign no need to create an APT update release just yet. I'm just trying to get the bootloader ready before the rpi-update firmware and fix any integration bugs.

**Comment by yassineim** [comment]
Much love 💖💖💖

**Comment by pepeEL** [comment]
When BIN will be available to test ?

**Comment by timg236** [comment]
soon

**Comment by pepeEL** [comment]
What you mean ? One day or more ?

**Comment by yassineim** [comment]
They said on the pull request it’s a matter of days

**Pull request merged**
