### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by lurch**
Fix date-typo in release-notes.md

### CODE REVIEW

**Comment by timg236** [comment]
It's better to have a descriptive name in the PR / commit because this ends up in the changelog

**Comment by lurch** [comment]
Have updated the PR text above. I didn't add a more-detailed description because I assumed a one-character typo wouldn't need an entry in the changelog??
Do I need to close this PR, and create a new commit where the comment is actually on the commit itself, rather than just the PR?

**Comment by timg236** [comment]
Changelogs are created automatically, I've pushed a commit anyway because I had to update for make-imager-release

**Comment by lurch** [comment]
> I've pushed a commit anyway

Cool.

**Pull request closed without merging**
