### PR TITLE
Create releases_CHS.md / 添加简体中文版 / Chinese version.

### PR DESCRIPTION
**Pull request by MasterYuan418**

### CODE REVIEW

**Comment by timg236** [comment]
How do you plan to keep this up to date?

**Comment by timg236** [comment]
@JamesH65 Add localized content here doesn't feel very scalable, how is this handled elsewhere? 

N.B. When a release is made only releases.md will be updated

**Comment by lurch** [comment]
AFAIK all the RPF-supported resources at https://projects.raspberrypi.org/ are [translated](https://projects.raspberrypi.org/), but all the RPT-supported documentation at https://www.raspberrypi.org/documentation/ is only available in English (see e.g. https://github.com/raspberrypi/documentation/search?q=translate&type=Issues ).

**Comment by JamesH65** [comment]
It's not something that has come up before. We don't have any translation in the documentation repo at all. We do have translations in NOOBS and PINN, perhaps they would be a better reference point?

**Comment by lurch** [comment]
But even then, the translations in NOOBS are for the NOOBS GUI application itself (i.e. handled by the [QT localisation process](https://github.com/raspberrypi/noobs/blob/master/README.md#addingupdating-translations) ), rather than any of the documentation _about_ NOOBS (which again is only available [in English](https://github.com/raspberrypi/noobs/blob/master/README.md) ).

**Comment by timg236** [comment]
I think localized content is best handled in the documentation repo although there are currently no structures for review or to ensure that the localized content is kept up to date.

I think readme.md can be deleted except for the list of links to the main documentation.

releases.md is more difficult because the links need to be updated when a release is made although it could become just a table of links to releases with a release information page in documentation (which could be localized)

**Comment by lurch** [comment]
@MasterYuan418 Forgive my ignorance, but how important is it to have the rpi-eeprom releases.md available in Chinese, given that all the rest of the [Raspberry Pi documentation](https://github.com/raspberrypi/documentation) is only available in English?

**Comment by MasterYuan418** [comment]
Ummm......You know,Our country's network isn't good.(GFW),So I can't fast and stable to link to raspberrypi.org.So may I help translate noobs or raspberry PI document?Sorry.Please ignore my ignorance.

**Comment by timg236** [comment]
> Ummm......You know,Our country's network isn't good.(GFW),So I can't fast and stable to link to raspberrypi.org.So may I help translate noobs or raspberry PI document?Sorry.Please ignore my ignorance.

For the moment you could fork the repo and share the link to that. I thought the existing translation projects applied to the technical docs as well, perhaps that's a future step

**Comment by MasterYuan418** [comment]
Copy that.I'm sorry to reply so late, because I have a very important exam for me recently.

**Pull request closed without merging**
