### PR TITLE
tools: rpi-otp-private-key: Update to same version as usbboot

### PR DESCRIPTION
**Pull request by timg236**

### CODE REVIEW

**Comment by timg236** [comment]
@peterharperuk Update the version in rpi-eeprom to contain the Pi5 enhancements. At some point usbboot needs to include rpi-eeprom as submodule to remove duplication.

**Comment by peterharperuk** [comment]
doh! Looks good

**Comment by lurch** [comment]
Does this mean that the bit at https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#device-specific-private-key which says "This is not yet implemented for BCM2712 devices" now needs removing?

**Comment by peterharperuk** [comment]
https://github.com/raspberrypi/documentation/issues/3548

**Comment by lurch** [comment]
Doh, sorry! :joy:

**Comment by peterharperuk** [comment]
np

**Pull request merged**
