### PR TITLE
2019-11-15 - Beta update for network boot fixes

### PR DESCRIPTION
**Pull request by timg236**
Fixes for TFTP_PREFIX handling plus option to force MAC_ADDRESS

### CODE REVIEW

**Comment by timg236** [comment]
@XECDesign @HiassofT hopefully this fixes the TFTP prefix handling, I need to redo the manual testing with various sd-cards so won't attempt to get an rpi-eeprom package update until early next week

**Comment by HiassofT** [comment]
thanks a lot for the fix!

LE netboot (with start.elf etc in a serial-number directory) works fine again with this version

**Comment by timg236** [comment]
Thanks for the test! I'm leaving a manufacturing soak test running over the weekend and do the manual SD-card testing next week. There's a performance tweak for EMMC sd-adapters but I'm hoping to create 
a firmware/stable series for this fairly soon to support people who rely upon Network Boot but don't want beta series.
Eventually stable would be promoted to critical but that could get combined with USB MSD in a combined update.

**Comment by timg236** [comment]
replaced with 2019-11-18 following a minor tidyup and change to enable high-speed on EMMC cards
https://github.com/timg236/rpi-eeprom/pull/new/pieeprom-2019-11-18

**Pull request closed without merging**
