### PR TITLE
Add make-beta-release as a wrapper around make-release

### PR DESCRIPTION
**Pull request by lurch**
Builds `beta_release/*.zip` from the latest files found in `firmware/beta/`

### CODE REVIEW

**Comment by timg236** [comment]
Perhaps the release name could be passed as a command-line argument so that this could be used with 'stable' or custom release names?

**Comment by lurch** [comment]
It _could_, but I kinda assumed that people would only ever want to use the recovery-mode to flash eeprom images for either the critical firmware (which is what `make-imager-release` does) **or** the very latest beta firmware (which is what `make-beta-release` does) ? :man_shrugging: 

But I've just pushed a tweak which borrows the inherit-value-from-envvar approach used by `rpi-update` :slightly_smiling_face:

**Comment by timg236** [comment]
> It _could_, but I kinda assumed that people would only ever want to use the recovery-mode to flash eeprom images for either the critical firmware (which is what `make-imager-release` does) **or** the very latest beta firmware (which is what `make-beta-release` does) ? 🤷‍♂️
> 
> But I've just pushed a tweak which borrows the inherit-value-from-envvar approach used by `rpi-update` 🙂

I think 'critical' release tends to be used by people who don't know about the bootloader and 'stable' is used by people who want new features which is quite common.

Now that the excitement over USB boot has faded away 'beta' is back to the original purpose i.e. support OS distro maintainers or to verify bug fixes

**Comment by timg236** [comment]
Merging looks good and thanks for the additions. I think it will end up being folded into make-release with proper command line args. I only added the script in the first release because I knew that if I had to generate 3 different bootloader variants I'd get at least one of them wrong at some point.

However, reading back through forum posts I can see this being useful for resellers / education etc so we might want to direct people towards these scripts via docs/forums as a handy way of creating an SD card to customize 10s of Pi4s / Pi400s

**Pull request merged**
