### PR TITLE
pieeprom-2021-03-04.bin - NVMe boot support - BETA

### PR DESCRIPTION
**Pull request by peterharperuk**
This add a new BETA version of the bootloader that supports nvme boot

### CODE REVIEW

**Comment by peterharperuk** [comment]
@timg236 Adding the nvme beta bootloader to rpi-eeprom

**Comment by timg236** [comment]
LGTM

**Comment by lurch** [comment]
Well that's curious... the "Files changed" tab on this commit shows 
image

but when I clone the repo, `ls -l firmware/beta/pieeprom-2021-03-04.bin` tells me that it has a size of 524288 bytes! :confused: :laughing:

**Comment by pelwell** [comment]
I noticed that last week - it's a GitHub glitch.

**Comment by timg236** [comment]
Yes, Github is a bit weird. If you clone the files/patch you get the correct result!

**Pull request merged**
