### PR TITLE
Debian/buster

### PR DESCRIPTION
**Pull request by XECDesign**

### CODE REVIEW

**Comment by lurch** [comment]
Fixes #113

**Comment by lurch** [comment]
@XECDesign Sorry for not thinking of this earlier, but should there be a post-install rule to delete the `pieeprom-2020-16-04.bin` file (if it exists) for the benefit of people who installed the previous version of the package? There's no "month 16" so there's no danger of that ever being a "valid" filename.

**Comment by XECDesign** [comment]
Do you mean from /boot or /lib? If from /boot, why? If from /lib, then dpkg removes previous files before updating a package, so it wouldn't be left behind.

**Comment by lurch** [comment]
> dpkg removes previous files before updating a package, so it wouldn't be left behind.

Ahh, didn't realise that! Everything's okay then :+1:

**Pull request merged**
