### PR TITLE
Refactor the imager script to reduce duplication and remove reliance on symlinks

### PR DESCRIPTION
**Pull request by lurch**
Just a suggestion... feel free to chop'n'change as you see fit :slightly_smiling_face:

### CODE REVIEW

**Comment by timg236** [comment]
It's an interesting idea but the reason I didn't parameterize it is that the imager only supports the production release.

**Comment by timg236** [comment]
Although thinking about this over some coffee, perhaps you could move this under a tools subdirectory and have a default configuration for 'build the default production release' and another option for build custom release.

I can this script being useful for someone who wants to take the latest stable release + chosen config to create a Pi updater SD-CARD e.g. network boot and latest EEPROM updater card for a classroom of Pis

**Comment by lurch** [comment]
> the imager only supports the production release.

Yup, and that's why the `FIRMWARE_RELEASE="critical"` is hardcoded as a constant (rather than being a command-line parameter).
In effect, all this PR does is change the "external interface" from:
```
./make-release 2020-09-03-vl805-000138a1
```
to:
```
./make-release 2020-09-03 000138a1
```
and get rid of the symlinks in the `imager` directory in the process. The output files it creates are the same.

> I can this script being useful for someone who wants to take the latest stable release + chosen config to create a Pi updater SD-CARD e.g. network boot and latest EEPROM updater card for a classroom of Pis

I hadn't even considered that, but I guess that's a possibility :slightly_smiling_face:

**Comment by timg236** [comment]
I was thinking that you could parameterize everything but have a trivial wrapper script to build the latest official release.

e.g. make-imager-release would just call make-release with the FW release dir, version, etc. We only change that when we want to bump the official release and anyone can re-run it without risking typing the wrong thing.

For custom releases, users can pass in whatever args they want or fork the repo with their alternate config files

**Comment by lurch** [comment]
Done that now :slightly_smiling_face:

**Comment by timg236** [comment]
Looks good, will give it a proper test on Monday and merge

**Comment by timg236** [comment]
LGTM

**Pull request merged**
