### PR TITLE
pieeprom-2022-04-26: Network install / secure-boot STABLE/BETA

### PR DESCRIPTION
**Pull request by timg236**
Candidate for the next default release.

### CODE REVIEW

**Comment by timg236** [comment]
@peterharperuk FYI this release enables network-install / HTTP download to be used with secure-boot

**Comment by lurch** [comment]
How is this both "beta" **and** "stable" ? :confused:

**Comment by peterharperuk** [comment]
@lurch Network install is in both beta and stable, so it's just the signing key that's changed.
@timg236 Do you want me to test this on a "secure" pi?

**Comment by lurch** [comment]
Ahhh, so the `pieeprom-2022-04-26.bin` in the beta directory is actually different to the `pieeprom-2022-04-26.bin` in the stable directory? (If so, I think that might be the first time that this has happened, which is why I was confused)

**Comment by timg236** [comment]
> How is this both "beta" **and** "stable" ? 😕

Same binary

**Comment by timg236** [comment]
> @lurch Network install is in both beta and stable, so it's just the signing key that's changed. @timg236 Do you want me to test this on a "secure" pi?

Yes, please. I have a pending commit which updates all the binaries in usbboot

**Pull request merged**
