### PR TITLE
Restore machine output exit code as string

### PR DESCRIPTION
**Pull request by MilhouseVH**
Also ensure 0 as default bootloader timestamp for both JSON and non-JSON.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Hang on... quick fix inbound.

**Comment by timg236** [comment]
No problem. I’m away from a computer right now but will merge it tomorrow. I’m planning to bump the vl805 binary (but not the bootloader ) from beta to critical to start the vli update for everyone.
Once we are sure it’s safe we’ll add rpi-eeprom to the apt update packages so everyone gets this.

**Comment by MilhouseVH** [comment]
OK thanks. I've applied the fix to this PR (and tested it) and it's working to my satisfaction now.

**Comment by timg236** [comment]
Thanks looks good

**Pull request merged**
