### PR TITLE
Promote 2020-04-16 to be the new default release as a critical update

### PR DESCRIPTION
**Pull request by timg236**
@XECDesign

### CODE REVIEW

**Comment by lurch** [comment]
@JamesH65 I guess this implies that the documentation needs to be updated to reflect the fact that network boot on the Pi4 is no longer a "beta feature" ?

**Comment by JamesH65** [comment]
I guess so, bootlfow_2711.md, plus there is a broken link on that page I just found that i will fix up at the same time.

**Comment by JamesH65** [comment]
OK done and merged to master.

**Comment by timg236** [comment]
Thanks!

**Pull request merged**
