### PR TITLE
Promote pieeprom-2021-11-22 beta release to stable

### PR DESCRIPTION
**Pull request by timg236**
* NVMe / PCIe reset fixes
* GPT / FAT enhancements
* FAT performance improvements
* Secure-boot for industrial customers (see usbboot repo)

### CODE REVIEW

**Comment by timg236** [comment]
@peterharperuk

**Comment by lurch** [comment]
Does the release-notes need to be updated?

**Comment by timg236** [comment]
> Does the release-notes need to be updated?

Good point, missing git add :)

**Comment by peterharperuk** [comment]
Looks good

**Pull request merged**
